root: true
env:
  browser: true
  es2020: true
extends:
  - airbnb-base
  - airbnb-typescript/base
ignorePatterns:
  - dist
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules:
  no-console: warn
